### ISSUE TITLE
Tests fail when executed within Eclipse

### ISSUE THREAD

**Issue by JanWittler** [vitruv-tools/Vitruv-CaseStudies#249]
There are many tests that currently fail when executed in Eclipse, but succeed when executed in Maven. From preliminary testing, it appears that this is not related to changes to the tests themselves, as even previously working versions of the tests fail with the same errors. Thus, my first guess is that changes to the underlying change propagation cause the errors.
Tests fail for the following projects (incomplete list):
- `tools.vitruv.applications.umljava.tests`
- `tools.vitruv.applications.pcmjava.tests`
- `tools.vitruv.applications.pcmjava.javaeditor.tests`

Projects not affected:
- `tools.vitruv.applications.pcmumlclass.tests`

Environment: Eclipse 06-2022, macOS 12.6 (aarch), Java 17.0.4.1

**Comment by JanWittler** [comment]
@tsaglam @TomWerm could you please check whether the tests also fail for Linux / Windows?

**Comment by TomWerm** [comment]
Environment: Eclipse 06-2022, Windows 11, Java 17.0.4.1, all tests are successful

**Comment by JanWittler** [comment]
Environment: Eclipse 06-2022, macOS 12.6 (aarch), Java 11.0.16.1_1, all tests are successful

So seems like a specific problem with Java 17 on macOS :/

**Comment by TomWerm** [comment]
Related to the JRE shipped with eclipse, happens on Windows too `Error in opening zip file: [...]\org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_17.0.3.v20220515-1416\jre\jmods\java.base.jmod`

**Comment by TomWerm** [comment]
Related to the Usage of a JRE (developer ressources are missing).
