### ISSUE TITLE
How to use the case studies

### ISSUE THREAD

**Issue by bjthehun** [vitruv-tools/Vitruv-CaseStudies#294]
I have recently installed the Vitruv Case studies and their dependencies into my Eclipse Modelling IDE, and now want to try them out. However, I cannot figure out how i can do that, and the wiki does not seem to contain any information on that, too.

So, how can I use these case studies?

**Comment by TomWerm** [comment]
The case studies are intended as system tests, using complex metamodels, defining complex consistency specifications, and executing changes to test them. Thus, they are used in our CI/CD pipeline and not to be used by users, but rather extended by developers by adding new metamodels and consistency specifications.

**Comment by bjthehun** [comment]
Oh. I thought these case studies were something that an interested user may try out.

Actually, is there some sort of tutorial or example for Vitruvius that I could use? I want to work with it, and did not find anything on the wiki.
